#!/usr/bin/env zsh

FILE=$1
SHELL=$2

if [ -v $FILE ]; then
    echo "File name was not specified"
    exit 1
fi

if [ -v $SHELL ]; then
    echo "Shell for the script was not specified"
    exit 1
fi

if ! type $SHELL > /dev/null; then
    echo "Specified shell not installed"
    exit 1
fi

if [ ! -f "$FILE" ]; then
    touch $FILE
    echo "#!/usr/bin/env $SHELL\n" > $FILE
    chmod +x $FILE
else
    echo "File already exists"
fi

